import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Card from '../../components/Card';
import Layout from '../../components/Layout';
import siteConfig from '../../site.config';
import { fetchPages } from '../../utils/notion';
import { IndexProps } from '../../types/types';

export const getStaticProps: GetStaticProps = async () => {
  const { results } = await fetchPages({});
  return {
    props: {
      pages: results ? results : [],
    },
    revalidate: 10,
  };
};

const Home: NextPage<IndexProps> = ({ pages }) => {
  return (
    <>
      <Head>
        <title>{siteConfig.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="pt-12">
          <h1 className="text-5xl mb-[32px] text-center text-base-white">
            {siteConfig.title}
          </h1>
          <div className="grid gap-[5rem] mt-[40px] grid-cols-2 w-[100%] my-[3rem]">
            {/* Card */}
            {pages.map((page, index) => (
              <Card key={index} page={page} />
            ))}
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
