import { sampleTypes } from '../types/types';
export const sampleCards = [
  {
    slug: 'red',
    name: 'Red',
    author: 'dog',
    cover: '/',
    published: '202x-xx-01',
    tags: ['Nest.js', 'Node.js'],
    content: 'Red page content',
  },
  {
    slug: 'white',
    name: 'White',
    author: 'cat',
    cover: '/',
    published: '202x-xx-02',
    tags: ['Notion'],
    content: 'White page content',
  },
  {
    slug: 'blue',
    name: 'Blue',
    author: 'bird',
    cover: '/',
    published: '202x-xx-03',
    tags: ['React'],
    content: 'Blue page content',
  },
  {
    slug: 'green',
    name: 'Green',
    author: 'pig',
    cover: '/',
    published: '202x-xx-04',
    tags: ['Vue.js'],
    content: 'Green page content',
  },
  {
    slug: 'black',
    name: 'Black',
    author: 'corw',
    cover: '/',
    published: '202x-xx-05',
    tags: ['Next.js', 'Nuxt.js'],
    content: 'Black page content',
  },
  {
    slug: 'emerald',
    name: 'Emerald',
    author: 'monster',
    cover: '/',
    published: '202x-xx-06',
    tags: ['Golang'],
    content: 'Emerald page content',
  },
  {
    slug: 'purple',
    name: 'Purple',
    author: 'elephant',
    cover: '/',
    published: '202x-xx-07',
    tags: ['PHP'],
    content: 'Purple page content',
  },
];
